-- MySQL Script generated by MySQL Workbench
-- Thu Nov 15 00:10:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbhorario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbhorario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbhorario` DEFAULT CHARACTER SET utf8 ;
USE `dbhorario` ;

-- -----------------------------------------------------
-- Table `dbhorario`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhorario`.`alumno` (
  `matricula` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(70) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbhorario`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhorario`.`materia` (
  `idmateria` INT NOT NULL AUTO_INCREMENT,
  `name_materia` VARCHAR(50) NOT NULL,
  `pre_materia` VARCHAR(50) NOT NULL,
  `post_materia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idmateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbhorario`.`materia_cursada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhorario`.`materia_cursada` (
  `alumno_matricula` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  `idmateriacursada` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_alumno_has_materia_materia1_idx` (`materia_idmateria` ASC),
  INDEX `fk_alumno_has_materia_alumno_idx` (`alumno_matricula` ASC),
  PRIMARY KEY (`idmateriacursada`),
  CONSTRAINT `fk_alumno_has_materia_alumno`
    FOREIGN KEY (`alumno_matricula`)
    REFERENCES `dbhorario`.`alumno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_materia_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `dbhorario`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbhorario`.`materia_ofertada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhorario`.`materia_ofertada` (
  `id_materiaofertada` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `profesor` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `salon` VARCHAR(45) NOT NULL,
  `edificio` VARCHAR(45) NOT NULL,
  `materia_idmateria` INT NOT NULL,
  PRIMARY KEY (`id_materiaofertada`),
  INDEX `fk_materia_ofertada_materia1_idx` (`materia_idmateria` ASC),
  CONSTRAINT `fk_materia_ofertada_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `dbhorario`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbhorario`.`horario_nuevo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbhorario`.`horario_nuevo` (
  `alumno_matricula` INT NOT NULL,
  `materia_ofertada_id_materiaofertada` INT NOT NULL,
  `idhorario` INT NOT NULL AUTO_INCREMENT,
  `materia_cursada_idmateriacursada` INT NOT NULL,
  INDEX `fk_alumno_has_materia_ofertada_materia_ofertada1_idx` (`materia_ofertada_id_materiaofertada` ASC),
  INDEX `fk_alumno_has_materia_ofertada_alumno1_idx` (`alumno_matricula` ASC),
  PRIMARY KEY (`idhorario`),
  INDEX `fk_horario_nuevo_materia_cursada1_idx` (`materia_cursada_idmateriacursada` ASC),
  CONSTRAINT `fk_alumno_has_materia_ofertada_alumno1`
    FOREIGN KEY (`alumno_matricula`)
    REFERENCES `dbhorario`.`alumno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_materia_ofertada_materia_ofertada1`
    FOREIGN KEY (`materia_ofertada_id_materiaofertada`)
    REFERENCES `dbhorario`.`materia_ofertada` (`id_materiaofertada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_nuevo_materia_cursada1`
    FOREIGN KEY (`materia_cursada_idmateriacursada`)
    REFERENCES `dbhorario`.`materia_cursada` (`idmateriacursada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
